@startuml
set namespaceSeparator none

class "Customer" {
  firstName : string {O}
  lastName : string {O}
}

class "CustomerId" <<Parameter>> {
  value : string
}
hide <<Method>> circle

class "GET /customer/expired" <<Method>> {
  customerId : string
}

class "GET /customer/expired 200 Response" <<Response>> {
}

"GET /customer/expired 200 Response" --> "*" "Customer"

"GET /customer/expired" ..> "GET /customer/expired 200 Response": 200

@enduml